name: Test Plugin

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run plugin structure test
      run: |
        python test_plugin.py

    - name: Test plugin import
      run: |
        python -c "
        import sys
        sys.path.insert(0, 'octoprint_psucontrol_tapo_p110')
        try:
            from PyP100 import PyP110
            print('✅ PyP100 import successful')
        except ImportError as e:
            print(f'❌ PyP100 import failed: {e}')
            sys.exit(1)
        "

    - name: Validate setup.py
      run: |
        python setup.py check

    - name: Check Python compatibility
      run: |
        python -c "
        import sys
        if sys.version_info < (3, 11):
            print(f'❌ Python {sys.version} is not supported. Requires 3.11+')
            sys.exit(1)
        else:
            print(f'✅ Python {sys.version} is supported')
        "

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install linting tools
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black

    - name: Lint with flake8
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        flake8 octoprint_psucontrol_tapo_p110 --count --select=E9,F63,F7,F82 --show-source --statistics
        # Exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 octoprint_psucontrol_tapo_p110 --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Check code formatting with black
      run: |
        black --check --diff octoprint_psucontrol_tapo_p110/
